;; ATTENTION: Run it in terminal in batch mode.
;;   emacs --script install-packages.el

(require 'package)
(package-initialize)

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

(package-list-packages)

;; Runs the installation of each package.
(package-install 'helm)
(package-install 'ess)
(package-install 'ess-view)
(package-install 'polymode)
(package-install 'poly-R)
(package-install 'poly-markdown)
(package-install 'poly-noweb)
(package-install 'ess-R-data-view)
(package-install 'auto-complete)
(package-install 'company)
(package-install 'bm)
(package-install 'smartparens)
(package-install 'yafolding)
(package-install 'magit)
(package-install 'markdown-mode)
(package-install 'markdown-toc)
(package-install 'neotree)
(package-install 'key-combo)
(package-install 'elpy)
(package-install 'jedi)
(package-install 'jedi-core)
(package-install 'solarized-theme)
(package-install 'move-text)
(package-install 'multiple-cursors)
(package-install 'imenu-list)
(package-install 'electric-spacing)
(package-install 'electric-operator)
(package-install 'auctex)
(package-install 'auctex-latexmk)
(package-install 'auctex-lua)
(package-install 'sublimity)
(package-install 'sublimity-scroll)
(package-install 'sublimity-map)
